### ISSUE TITLE
process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see 

### ISSUE THREAD

**Issue by bsed** [ConProgramming/junglejs#20]
```bash
js\jungle-app\jungle\build\blog\100-practical-experiences-of-seo-god-i-1\main.js
    at Object.pp$4.raise (D:\work\zhaoxf\js\jungle-app\node_modules\rollup\dist\shared\rollup.js:3921:13)
    at Object.pp$9.invalidStringToken (D:\work\zhaoxf\js\jungle-app\node_modules\rollup\dist\shared\rollup.js:5868:10)
    at Object.pp$9.readEscapedChar (D:\work\zhaoxf\js\jungle-app\node_modules\rollup\dist\shared\rollup.js:5982:14)
    at Object.pp$9.readString (D:\work\zhaoxf\js\jungle-app\node_modules\rollup\dist\shared\rollup.js:5834:19)
    at Object.pp$9.getTokenFromCode (D:\work\zhaoxf\js\jungle-app\node_modules\rollup\dist\shared\rollup.js:5654:17)
    at Object.getTokenFromCode (D:\work\zhaoxf\js\jungle-app\node_modules\rollup\dist\shared\rollup.js:18502:20)
    at Object.pp$9.readToken (D:\work\zhaoxf\js\jungle-app\node_modules\rollup\dist\shared\rollup.js:5403:15)
    at Object.pp$9.nextToken (D:\work\zhaoxf\js\jungle-app\node_modules\rollup\dist\shared\rollup.js:5394:15)
    at Object.pp$9.next (D:\work\zhaoxf\js\jungle-app\node_modules\rollup\dist\shared\rollup.js:5351:8)
    at Object.pp.eatContextual (D:\work\zhaoxf\js\jungle-app\node_modules\rollup\dist\shared\rollup.js:1639:8)
(node:11848) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11848) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
If you need MD file, please mail me. me@gnux.cn

**Comment by ConProgramming** [comment]
Hi, could you give any more info on what caused this?
